apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanner
            image: mauriche/scanner:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
      backoffLimit: 0
